package entity

const (
	// Eventos de Vault
	VAULT_CREATED  EventType = "VAULT_CREATED"
	VAULT_ACCESSED EventType = "VAULT_ACCESSED"
	VAULT_MODIFIED EventType = "VAULT_MODIFIED"
	VAULT_DELETED  EventType = "VAULT_DELETED"
	VAULT_SHARED   EventType = "VAULT_SHARED"

	// Eventos de Secret
	SECRET_CREATED  EventType = "SECRET_CREATED"
	SECRET_ACCESSED EventType = "SECRET_ACCESSED"
	SECRET_MODIFIED EventType = "SECRET_MODIFIED"
	SECRET_DELETED  EventType = "SECRET_DELETED"
	SECRET_EXPORTED EventType = "SECRET_EXPORTED"

	// Eventos de Permissão
	PERMISSION_GRANTED EventType = "PERMISSION_GRANTED"
	PERMISSION_REVOKED EventType = "PERMISSION_REVOKED"
	ACCESS_DENIED      EventType = "ACCESS_DENIED"

	// Eventos de Sistema
	TOKEN_GENERATED     EventType = "TOKEN_GENERATED"
	TOKEN_REVOKED       EventType = "TOKEN_REVOKED"
	SUSPICIOUS_ACTIVITY EventType = "SUSPICIOUS_ACTIVITY"
)
