# Configuração do Prometheus para monitoramento do OpenFGA

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Monitoramento do OpenFGA
  - job_name: 'openfga'
    static_configs:
      - targets: ['openfga:2112']
    scrape_interval: 5s
    metrics_path: /metrics
    
  # Monitoramento do Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  # Monitoramento do PostgreSQL (se exportador estiver habilitado)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 10s
    
  # Monitoramento do Redis (se exportador estiver habilitado)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 10s

# Configurações de alertas (opcional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
